name: "Build Indices"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1,3,5'
jobs:
  pin-nixpkgs:
    name: Pin nixpkgs revision
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [ nixpkgs-unstable ]
    steps:
    - name: Fetch nixpkgs revision
      run: curl https://api.github.com/repos/NixOS/nixpkgs/git/refs/heads/${{ matrix.channel }} | jq .object.sha | tr -d \" > revision.txt
    - name: Upload revision artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact-${{ matrix.channel }}-revision
        path: revision.txt

  build-database:
    name: Build database
    runs-on: ubuntu-latest
    needs: pin-nixpkgs
    strategy:
      matrix:
        channel: [ nixpkgs-unstable ]
        platform: [ aarch64-darwin, aarch64-linux, i686-linux, x86_64-darwin, x86_64-linux ]
    steps:
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz
    - uses: cachix/cachix-action@v10
      with:
        name: nix-index
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Download revision artifact
      uses: actions/download-artifact@v3
      with:
        name: artifact-${{ matrix.channel }}-revision
    - name: Run nix-index
      run: nix shell github:usertam/nix-index -c nix-index --db ./out --nixpkgs https://github.com/NixOS/nixpkgs/tarball/$(<revision.txt) --system ${{ matrix.platform }} 2>&1 | grep -v '+ generating index'
    - name: Rename built index
      run: mv out/files index-${{ matrix.platform }}
    - name: Upload index artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact-${{ matrix.channel }}-${{ matrix.platform }}
        path: index-${{ matrix.platform }}

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build-database
    strategy:
      matrix:
        channel: [ nixpkgs-unstable ]
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/nixpkgs-unstable.tar.gz
    - name: Set up github-actions name and email
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Move artifacts
      run: |
        mv artifact-${{ matrix.channel }}-*/* .
        mkdir indices
        mv index-* indices
    - name: Generate generic release tag
      id: tag
      run: echo "::set-output name=tag::$(echo `date +'%y%m%d'`.`grep -oE '^.{7}' revision.txt`)"
    - name: Assert release tag is available
      run: |
        ! git ls-remote --exit-code origin "refs/tags/r${{ steps.tag.outputs.tag }}"
    - name: Generate release flake and metadata
      run: |
        cp releases/flake.nix .
        python3 releases/describe.py "r${{ steps.tag.outputs.tag }}" ${{ matrix.channel }} $(<revision.txt)
    - name: Commit to releases/${{ matrix.channel }}
      run: |
        git fetch origin releases/${{ matrix.channel }}:releases/${{ matrix.channel }} || true
        git symbolic-ref HEAD refs/heads/releases/${{ matrix.channel }}
        git reset
        nix flake update
        git add flake.nix flake.lock metadata.json indices
        git commit -m "release ${{ steps.tag.outputs.tag }}"
        git tag "r${{ steps.tag.outputs.tag }}"
        git push origin releases/${{ matrix.channel }} "r${{ steps.tag.outputs.tag }}"
    - name: Generate standalone flake and metadata
      run: |
        cp standalone/flake.nix .
        python3 standalone/describe.py "s${{ steps.tag.outputs.tag }}" ${{ matrix.channel }} $(<revision.txt)
    - name: Commit to standalone/${{ matrix.channel }}
      run: |
        git fetch origin standalone/${{ matrix.channel }}:standalone/${{ matrix.channel }} || true
        git symbolic-ref HEAD refs/heads/standalone/${{ matrix.channel }}
        git reset
        nix flake update
        git add flake.nix flake.lock metadata.json
        git commit -m "standalone release ${{ steps.tag.outputs.tag }}"
        git tag "s${{ steps.tag.outputs.tag }}"
        git push origin standalone/${{ matrix.channel }} "s${{ steps.tag.outputs.tag }}"
    - name: Format release body
      run: |
        >> release.md echo "- Built against channel: [\`${{ matrix.channel }}\`](https://github.com/nixos/nixpkgs/tree/${{ matrix.channel }})"
        >> release.md echo "- Built against commit: [\`$(grep -oE '^.{7}' revision.txt)\`](https://github.com/NixOS/nixpkgs/commit/$(<revision.txt))"
        >> release.md echo "- Build date: \`$(date)\`"
    - uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: "r${{ steps.tag.outputs.tag }}"
        body_path: release.md
        tag_name: "r${{ steps.tag.outputs.tag }}"
        files: |
          indices/index-*
          revision.txt
